"""Organizational authorization, independent of registration and profiles."""

from .store import (
    BUSINESS_ADMIN,
    DAILY_RECEIVE,
    DRIVER_READ,
    DRIVER_RECEIVE,
    DRIVER_REPORT_READ,
    FILE_RESOURCES,
    FUNCTION_CAPABILITIES,
    FUNCTION_READ,
    MAINTENANCE_RECORDS_READ,
    MECH_DRIVER_RECEIVE,
    MECH_OVERFLOW_RECEIVE,
    MECHANICAL_MANAGER,
    MECHANICAL_MANAGER_DEPUTY,
    MECHANICAL_STAFF,
    OFFICE_SUPERVISOR,
    OVERFLOW_READ,
    AuthorizationStore,
    FunctionScope,
    RecipientSetResolution,
)

# Public package API; these imports are intentional re-exports.
__all__ = [
    "BUSINESS_ADMIN",
    "DAILY_RECEIVE",
    "DRIVER_READ",
    "DRIVER_RECEIVE",
    "DRIVER_REPORT_READ",
    "FILE_RESOURCES",
    "FUNCTION_CAPABILITIES",
    "FUNCTION_READ",
    "MAINTENANCE_RECORDS_READ",
    "MECHANICAL_MANAGER",
    "MECHANICAL_MANAGER_DEPUTY",
    "MECHANICAL_STAFF",
    "MECH_DRIVER_RECEIVE",
    "MECH_OVERFLOW_RECEIVE",
    "OFFICE_SUPERVISOR",
    "OVERFLOW_READ",
    "AuthorizationStore",
    "FunctionScope",
    "RecipientSetResolution",
]
